
version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./data:/app/data
    environment:
      - ADMIN_API_KEY=your_super_secret_admin_key
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
